### ISSUE TITLE
some error about code

### ISSUE THREAD

**Issue by billy800413** [HadoopIt/rnn-nlu#8]
First, thanks for your code 
when I train the model, I met an error about iteritems and terminal say: "AttributeError: 'dict' object has no attribute 'iteritems' "  
How can I solve the problem
                                                        thanks

**Comment by HadoopIt** [comment]
Sorry for the delayed updates. The code is now updated to work with the latest TensorFlow API r1.2. 

The error you had should be related to Python 3. You may either update the dict.iteritems() to dict.items(), or run it with Python 2.
